language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t luissilva1111511/dockertuto:dev -f Dockerfile.dev .
script:
  - docker run -e CI=true luissilva1111511/dockertuto:dev npm run test