version: '3'
services:
  frontend:
    image: luissilva1111511/frontend:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "80:3000"
    volumes:
      - /app/node_modules
      # - .:/app
  
  frontend-tests:
    image: luissilva1111511/frontend:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      # - .:/app
    command: ["npm", "run", "test"]